## Bluetooth policy for the BT-50 PRO.
## Keep the BT-50 PRO on its high-fidelity A2DP profile.

wireplumber.settings = {
  bluetooth.autoswitch-to-headset-profile = false
}

monitor.bluez.properties = {
  bluez5.enable-msbc = true
}

device.profile.priority.rules = [
  {
    matches = [
      {
        device.name = "bluez_card.00_02_5B_00_FF_0E"
      }
    ]
    actions = {
        update-props = {
          priorities = [
          "a2dp-sink",
          "a2dp-sink-aac",
          "a2dp-sink-sbc_xq",
          "a2dp-sink-sbc",
          "a2dp-sink-aptx_hd",
          "a2dp-sink-aptx",
          "a2dp-sink-aptx_ll",
          "headset-head-unit",
          "headset-head-unit-cvsd"
        ]
      }
    }
  }
]
