set -g default-shell /bin/zsh
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc,xterm-kitty:Tc"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g display-time 1500
set -g mouse on
set -g escape-time 0
set -g focus-events on
set -g extended-keys on
set -g set-titles on
set -g set-titles-string "#S - #W"

bind -n M-e new-window -c "#{pane_current_path}"
bind -n M-h previous-window
bind -n M-l next-window
bind -n M-, swap-window -t -1\; previous-window
bind -n M-. swap-window -t +1\; next-window
bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9
bind -n M-0 select-window -t :10

bind -n M-w split-window -h -l 40% -c "#{pane_current_path}"
bind -n M-q kill-pane
bind -n M-u select-pane -L
bind -n M-r run-shell '~/.config/scripts/toggle-opencode.sh'
bind -n M-t run-shell '~/.config/scripts/toggle-claudecode.sh'
bind -n M-i resize-pane -L 5
bind -n M-o resize-pane -R 5

set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-justify left

set -g status-style "bg=#0f0f0f,fg=#9e9e9e"
set -g status-left "[#S] "
set -g status-left-length 20
set -g status-right "%H:%M %d-%b-%y"
set -g status-right-length 40

set -g window-status-format " #I:#W "
set -g window-status-style "bg=#121212,fg=#9e9e9e"
set-window-option -g window-status-current-style bg=red,fg=#0f0f0f
set -g pane-border-style "fg=#3f3f3f"
set -g pane-active-border-style "fg=#5f5f5f"
set -g message-style "bg=#232323,fg=#ffffff"
