#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fail() { echo "qml.test: $*" >&2; exit 1; }

grep -q 'id: afterPeakMonitor' "$root/Panel.qml" || fail "Panel needs afterPeakMonitor"
grep -q 'PwNode.name is constant' "$root/Service.qml" || fail "tracker must not bind omavoice while name is empty"
grep -q 'node.always-process' "$root/scripts/omavoice-run" && fail "always-process destroys the source when capture target is not ready"
grep -q 'id: rowPeak' "$root/Panel.qml" || fail "each mic row needs a peak monitor"
grep -q 'PwNodePeakMonitor' "$root/Panel.qml" || fail "Panel must use PwNodePeakMonitor"
grep -q 'afterPeakMonitor.peak' "$root/Panel.qml" || fail "selected row must show After"
grep -q 'enabled: root.opened && root.metersArmed && sourceRow.isActive && !!node' "$root/Panel.qml" || fail "row meters must run only on the selected mic"
grep -q 'onAfterNodeNameChanged' "$root/Service.qml" || fail "hold must wait for the bound Omavoice name"
grep -q 'onAfterNodeIdChanged' "$root/Service.qml" || fail "hold must retarget when omavoice is a new node"
grep -q 'meterHoldTarget === token' "$root/Service.qml" || fail "meter hold must key the node id, not only the name omavoice"
grep -q 'afterHoldKey' "$root/Panel.qml" || fail "panel must re-arm After hold when the omavoice id changes"
grep -q 'id: meterHoldWatch' "$root/Service.qml" || fail "hold must retry if it never started"
grep -q 'startDebounce' "$root/Service.qml" || fail "preset switches must debounce the host restart"
grep -q 'shouldDeferSourcePick' "$root/Service.qml" || fail "source pick must ignore unbound-name flicker"
grep -q 'pickFallbackName' "$root/Service.qml" || fail "Auto must use a remembered capture when default is omavoice"
grep -q 'previousAudioSource' "$root/Service.qml" || fail "Service must persist the real capture before promote"
grep -q 'previousDefaultName' "$root/Service.qml" && fail "do not restore omavoice as the previous default"
grep -q 'restoreCaptureName' "$root/Service.qml" || fail "restoreDefault must use restoreCaptureName"
grep -q 'function restoreCaptureName' "$root/Model.js" || fail "restoreCaptureName must refuse omavoice names"
grep -q 'Util.alpha' "$root/Panel.qml" || fail "meters must use Omarchy audio chrome"
grep -q 'setMeterHold' "$root/Service.qml" || fail "Service must expose setMeterHold"
grep -q 'function armMeterHold' "$root/Panel.qml" || fail "panel must re-arm After hold after a plugin reload"
grep -q 'visible: sourceRow.isActive && !!service.afterNode' "$root/Panel.qml" || fail "After hairline must follow the omavoice node, not hostProcess.running"
grep -q 'function rebuildHost' "$root/Service.qml" && fail "do not restart the host to fake Input/Output"
grep -q 'preamp:Gain 1' "$root/Service.qml" && fail "live ctl must not write preamp; isolated mixers do not move"
grep -q 'meterHoldWanted && enabled && !!token' "$root/Service.qml" || fail "meter hold must not wait on hostProcess.running"
grep -q 'onServiceChanged' "$root/Panel.qml" || fail "panel must rebind the service after a plugin reload"
grep -q 'pgrep -x pipewire' "$root/scripts/omavoice-run" || fail "host start must drop leftover pipewire by comm, not argv text"
grep -q 'pkill -f "/pipewire -c $conf"' "$root/scripts/omavoice-run" && fail "pkill -f on the conf path kills unrelated shells"
grep -qF 'host.$$.conf' "$root/scripts/omavoice-run" || fail "live host conf must be pid-unique so remounts cannot truncate it"
grep -q 'umask 077' "$root/scripts/omavoice-run" || fail "host conf must not be world-readable"
grep -qF 'target =~ ^[A-Za-z0-9._:-]+$' "$root/scripts/omavoice-run" || fail "host must reject junk --target names"
grep -q 'wait_session' "$root/scripts/omavoice-run" || fail "host start must wait for the session core"
grep -q 'omavoice_in_graph' "$root/scripts/omavoice-run" || fail "host start must wait for leftover omavoice nodes to leave"
grep -q 'destroy_leftover_nodes' "$root/scripts/omavoice-run" || fail "preset switch must destroy leftover omavoice nodes"
grep -q 'pipewire -c "$conf" &' "$root/scripts/omavoice-run" || fail "host must supervise pipewire until omavoice is in the session"
grep -q 'exec /usr/bin/pipewire -c' "$root/scripts/omavoice-run" && fail "exec leaves an empty D-Bus pipewire with no omavoice node"
grep -q 'omavoice did not appear in PipeWire' "$root/scripts/omavoice-run" || fail "host must exit if omavoice never joins the session"
grep -q 'pipewire.sec.pid' "$root/scripts/omavoice-run" || fail "host must require a session client, not a D-Bus-only pipewire"
grep -q 'os.system' "$root/scripts/omavoice-run" && fail "destroy_leftover_nodes must not interpolate pw-dump ids into a shell"
grep -q 'subprocess.run' "$root/scripts/omavoice-run" || fail "destroy leftover nodes with a fixed argv pw-cli"
grep -q '"pw-cli", "destroy"' "$root/scripts/omavoice-run" || fail "leftover omavoice nodes must be destroyed by id via argv"
grep -q 'isinstance(oid, bool)' "$root/scripts/omavoice-run" || fail "PipeWire ids must reject bool (int subclass)"
grep -q 'leftover omavoice nodes still in the session' "$root/scripts/omavoice-run" && fail "do not fail the host start because Meeting AEC names linger"
grep -q 'id: hostBindWatch' "$root/Service.qml" || fail "empty host must restart until the omavoice node appears"
grep -q 'hostProcess.running && hostKey === key) return' "$root/Service.qml" || fail "do not restart the host on every PipeWire node change"
grep -q 'pickChanged || !hostProcess.running' "$root/Service.qml" || fail "source refresh must not restart a live host"
grep -q 'defaultSourceName === Model.NODE_NAME' "$root/Service.qml" || fail "After must bind the default source when it is omavoice"
grep -A12 'id: hostBindWatch' "$root/Service.qml" | grep -q 'if (hostProcess.running) return' \
  || fail "bind watch must not kill a live wrapper"
grep -q 'hostAttempts >= 8' "$root/Service.qml" || fail "start error only after retries are exhausted"
grep -A20 'id: hostProcess' "$root/Service.qml" | grep -q startDebounce \
  && fail "hostProcess stop must not startDebounce; overlapping omavoice-run deletes the next conf"
grep -q '/proc/$pid' "$root/scripts/omavoice-run" || fail "stale host conf must not delete a live pid's file"
grep -q 'Could not start the microphone.' "$root/Model.js" || fail "bind failure copy lives in Model.hostErrorText"
grep -q "Couldn't start" "$root/Panel.qml" || fail "hero must not shout the long error"
grep -q 'text: service.lastError' "$root/Panel.qml" || fail "error body is shown once under the header"
grep -q 'hostAttempts' "$root/Service.qml" || fail "host restarts must cap so a broken graph cannot loop"
grep -q 'anchors.right: sourceRow.isActive ? levelHit.left' "$root/Panel.qml" && fail "row click must not anchor to nested levelHit"
grep -q 'pw-cat' "$root/Service.qml" || fail "Service must hold the graph with pw-cat"
grep -q '"--target", name' "$root/Service.qml" || fail "pw-cat must target the bound omavoice name"
grep -q '"--target", nodeId' "$root/Service.qml" && fail "pw-cat must not target Quickshell node ids"
grep -q 'node.dont-fallback=true' "$root/Service.qml" && fail "pw-cat dont-fallback prevents the meter hold from attaching"
grep -q '/dev/null' "$root/Service.qml" || fail "meter hold must discard audio"
grep -q 'afterNodeName' "$root/Service.qml" || fail "Service must expose the bound afterNodeName"
grep -q 'afterNode' "$root/Service.qml" || fail "Service must expose afterNode"
grep -q 'nodeNamed' "$root/Service.qml" || fail "Service must look up capture nodes by name"
grep -q '"version": "0.3.2"' "$root/manifest.json" || fail "manifest must be 0.3.2"
grep -q 'text: "Voice"' "$root/Panel.qml" || fail "tune page must have a Voice section"
grep -q 'id: tuneFlick' "$root/Panel.qml" || fail "tune page must scroll when Voice does not fit"
grep -q 'eq_body:Gain' "$root/Service.qml" || fail "live controls must write eq_body Gain"
grep -q 'eq_pres:Gain' "$root/Service.qml" || fail "live controls must write eq_pres Gain"
grep -q 'eq_air:Gain' "$root/Service.qml" || fail "live controls must write eq_air Gain"
grep -q 'hp:Freq' "$root/Service.qml" || fail "live controls must write hp Freq"
grep -q 'preset + "\\0" + engine + "\\0" + targetName' "$root/Service.qml" || fail "hostKey must stay preset+engine+target"
key_line=$(grep 'var key = preset' "$root/Service.qml" || true)
[[ -n $key_line ]] || fail "hostKey must build var key from preset"
echo "$key_line" | grep -q 'eq' && fail "host key must not include EQ"
grep -q 'text: "DISABLED"' "$root/Panel.qml" || fail "Clean Voice must show DISABLED beside the title"
grep -q 'enabled: service.preset !== "clean"' "$root/Panel.qml" || fail "Voice controls must disable on Clean"
grep -q 'visible: service.preset !== "clean"' "$root/Panel.qml" && fail "Voice controls must stay visible on Clean"
grep -q 'Clean has no voice EQ' "$root/Panel.qml" && fail "Clean Voice must not use the orphan caption"
grep -q 'Clean is a high-pass' "$root/Panel.qml" && fail "Clean Voice is DISABLED, not a caption"
grep -q 'eqCurveHint' "$root/Panel.qml" || fail "Voice chips need hover tips"
grep -q '{ value: "clear", label: "Clear" }' "$root/Panel.qml" || fail "Voice looks must include Clear"
grep -q '{ value: "bright", label: "Bright" }' "$root/Panel.qml" || fail "Voice looks must include Bright"
grep -q '{ value: "presence", label: "Presence" }' "$root/Panel.qml" && fail "Presence is a slider, not a Voice look"
grep -q '{ value: "air", label: "Air" }' "$root/Panel.qml" && fail "Air is a slider, not a Voice look"
grep -q 'title: "Presence"' "$root/Panel.qml" || fail "Presence slider must stay"
grep -q 'title: "Air"' "$root/Panel.qml" || fail "Air slider must stay"
grep -q '"clear"' "$root/manifest.json" || fail "schema looks must include clear"
grep -q '"bright"' "$root/manifest.json" || fail "schema looks must include bright"
grep -q '"podcastEq": "clear"' "$root/manifest.json" || fail "Podcast default look is Clear"
grep -q 'function setEqCurve' "$root/Panel.qml" || fail "look chips must call setEqCurve"
grep -q 'onClicked: root.setEqCurve' "$root/Panel.qml" || fail "look chips must click through setEqCurve"
grep -Fq 'patch[prefix + "BodyDb"] = 0' "$root/Panel.qml" || fail "look click must zero Body trim"
grep -Fq 'patch[prefix + "PresenceDb"] = 0' "$root/Panel.qml" || fail "look click must zero Presence trim"
grep -Fq 'patch[prefix + "AirDb"] = 0' "$root/Panel.qml" || fail "look click must zero Air trim"
grep -q 'component VoiceRow' "$root/Panel.qml" || fail "Voice knobs must not reuse the ±12 Input/Output row"
grep -q 'snapEqBandDb' "$root/Panel.qml" || fail "Voice knobs must clamp writes to look ±6"
grep -q 'eqBandRange' "$root/Panel.qml" && fail "Voice knobs must stay on a fixed ±12 scale so looks move the thumbs"
grep -q 'persisted: service.eqBodyDb' "$root/Panel.qml" || fail "Body slider must show the curve, not only trim"
grep -q 'eqBodyDb' "$root/Service.qml" || fail "Service must expose eqBodyDb as a real"
grep -q '"--eq"' "$root/Service.qml" || fail "host must pass --eq"
grep -q 'meetingEq' "$root/manifest.json" || fail "schema needs meetingEq"
grep -q 'podcastEq' "$root/manifest.json" || fail "schema needs podcastEq"
[[ -f "$root/preview.png" ]] || fail "marketplace needs root preview.png"
[[ -f "$root/docs/preview-tune.png" ]] || fail "preset tune screenshot must be in docs"
grep -q 'id: reloadButton' "$root/Panel.qml" || fail "header needs a reload next to on/off"
grep -q 'iconText: service.busyReason === "reload" || service.reloading ? "󰑓" : "󰑐"' "$root/Panel.qml" || fail "reload must use the HEY/Fizzy refresh icons"
grep -q 'function reload' "$root/Service.qml" || fail "Service must expose reload"
grep -q 'libdeep_filter_ladspa-bin' "$root/README.md" || fail "Podcast AUR package must be libdeep_filter_ladspa-bin"
grep -q 'deepfilternet-ladspa' "$root/README.md" && fail "deepfilternet-ladspa is not an AUR package"
grep -q 'mktemp' "$root/scripts/omavoice-run" || fail "--dump must write a temp conf, not the live host"
grep -q 'n.isStream && name !== Model.NODE_NAME' "$root/Service.qml" || fail "tracker must bind named sources, including omavoice"
grep -q 'onNodesChanged:' "$root/Service.qml" || fail "sources must refresh on PipeWire node changes"
grep -A3 'onNodesChanged:' "$root/Service.qml" | grep -q 'refreshSources' || fail "node changes must still refresh sources"
grep -q 'plugins.omarchy.org' "$root/README.md" || fail "README must point at the official marketplace"
grep -q 'omarchyplugins.com' "$root/README.md" && fail "README must not use omarchyplugins.com"
[[ -e "$root/omavoice.png" ]] && fail "root omavoice.png leftover orb must be gone"
grep -q 'microphone.svg' "$root/OmavoiceIcon.qml" || fail "icon must use the microphone SVG"
grep -q 'docs/omavoice.svg' "$root/README.md" || fail "README must use the microphone banner"
grep -q 'Softer' "$root/Panel.qml" || fail "quality stops must be Softer / Balanced / Stronger"
grep -q 'qualityHint' "$root/Panel.qml" || fail "quality slider must explain the impact"
grep -q 'Your voice, better heard' "$root/README.md" || fail "README must keep the tagline"
grep -q 'component QualitySlider' "$root/Panel.qml" || fail "settings need a 3-stop quality slider"
grep -q 'meetingQuality' "$root/Service.qml" || fail "Service must expose meetingQuality"
grep -q '"--quality"' "$root/Service.qml" || fail "host must pass --quality"
grep -q '"--engine"' "$root/Service.qml" || fail "host must pass --engine"
grep -q '"--capture-gain-db"' "$root/Service.qml" || fail "host must bake capture gain"
grep -q '"--output-gain-db"' "$root/Service.qml" || fail "host must bake output gain"
grep -q 'omavoice-ctl' "$root/Service.qml" || fail "live controls must use omavoice-ctl"
grep -q 'args.push("--id", captureNodeId)' "$root/Service.qml" && fail "live controls must look up omavoice.capture by name, not Quickshell ids"
grep -q 'CAPTURE_NAME' "$root/Service.qml" || fail "tracker must bind omavoice.capture"
grep -q 'aec-sync' "$root/Service.qml" || fail "Meeting must still run aec-sync to drop classic AEC links"
grep -q 'aec-sync' "$root/scripts/omavoice-ctl" || fail "omavoice-ctl must implement aec-sync"
grep -q 'pw-link' "$root/scripts/omavoice-ctl" && fail "aec-sync must not pw-link the default sink into omavoice.aec.sink"
grep -q 'if real:' "$root/scripts/omavoice-ctl" || fail "aec-sync must leave monitor.mode links alone during a call"
grep -q 'function setEngine' "$root/Panel.qml" || fail "tune page must set engine"
grep -q 'function setOutputGainDb' "$root/Panel.qml" && fail "Input/Output faders must be gone"
grep -q 'function setCaptureGainDb' "$root/Panel.qml" && fail "Input/Output faders must be gone"
grep -q 'property bool levelOpen' "$root/Panel.qml" && fail "Level drawer must be gone"
grep -q 'text: "Level"' "$root/Panel.qml" && fail "Level chevron must be gone"
grep -q 'title: "Output"' "$root/Panel.qml" && fail "Output fader must be gone"
grep -q 'title: "Input"' "$root/Panel.qml" && fail "Input fader must be gone"
grep -q 'property real held' "$root/Panel.qml" || fail "GainRow must hold the snapped value so the knob stays"
grep -q 'engineChoiceHint' "$root/Panel.qml" || fail "engine chips need hover tips"
grep -q 'engineSetting === "auto" && service.engine === modelData.value' "$root/Panel.qml" || fail "live-engine dot only when Auto is picked"
grep -q 'engineUsingLine' "$root/Panel.qml" && fail "do not print Using … under the engine chips"
grep -q 'levelOpen ? "󰅀" : "󰅁"' "$root/Panel.qml" && fail "Level chevron must be gone"
grep -q 'snapGainDb' "$root/Panel.qml" || fail "Voice knobs must snap to 0.5 dB"
grep -q 'function snapGainDb' "$root/Model.js" || fail "snapGainDb lives in Model"
grep -q 'function previewGains' "$root/Service.qml" && fail "do not preview Input/Output; the faders are gone"
grep -q 'function clearGainPreview' "$root/Service.qml" && fail "gain preview must be gone"
grep -q 'Level into noise suppression' "$root/Panel.qml" && fail "NS caption must be gone"
grep -q 'text: "Out"' "$root/Panel.qml" && fail "Out shorthand must be gone"
grep -q 'text: "In"' "$root/Panel.qml" && fail "In shorthand must be gone"
grep -q '"outputGainDb"' "$root/manifest.json" || fail "schema keeps outputGainDb for a later live path"
grep -q '"captureGainDb"' "$root/manifest.json" || fail "schema keeps captureGainDb for a later live path"
grep -q 'meetingOutputGainDb: db' "$root/Panel.qml" && fail "do not persist Level keys; faders are gone"
grep -q 'formatGainDb(held)' "$root/Panel.qml" || fail "Voice label must show the thumb, not a stale persisted dB"
grep -q 'dragging ? held : persisted' "$root/Panel.qml" && fail "Level label must not fall back to persisted on release"
grep -q 'Binding on held {' "$root/Panel.qml" && fail "GainRow must not rebind held when the slider drops dragging"
grep -q 'property real lastSent' "$root/Panel.qml" || fail "GainRow must persist the last dragged value, not the stale released() arg"
grep -q 'preset + "\\0" + engine + "\\0" + targetName' "$root/Service.qml" || fail "hostKey must include engine"
grep -q 'String(captureGainDb) + "\\0" + String(outputGainDb)' "$root/Service.qml" && fail "hostKey must not restart on dormant Input/Output settings"
grep -q 'preset + "\\0" + quality + "\\0"' "$root/Service.qml" && fail "hostKey must not include quality"
grep -q 'onQualityChanged: applyLiveControls' "$root/Service.qml" || fail "quality must apply live"
grep -q 'onOutputGainDbChanged' "$root/Service.qml" && fail "Output must not drive the host; faders are gone"
grep -q 'onCaptureGainDbChanged' "$root/Service.qml" && fail "Input must not drive the host; faders are gone"
grep -q 'id: liveCtlProcess' "$root/Service.qml" || fail "EQ/quality live writes still use a Process"
grep -q 'onEqBodyDbChanged: applyLiveControls' "$root/Service.qml" || fail "body trim must apply live"
grep -q 'onEqPresDbChanged: applyLiveControls' "$root/Service.qml" || fail "presence trim must apply live"
grep -q 'onEqAirDbChanged: applyLiveControls' "$root/Service.qml" || fail "air trim must apply live"
grep -q 'readonly property real eqBodyDb: eqBands.body' "$root/Service.qml" || fail "eqBodyDb must be a real from eqBands"
grep -q 'readonly property real eqPresDb: eqBands.pres' "$root/Service.qml" || fail "eqPresDb must be a real from eqBands"
grep -q 'readonly property real eqAirDb: eqBands.air' "$root/Service.qml" || fail "eqAirDb must be a real from eqBands"
eq_gain_calls=$(grep -c 'Model.eqBandGains' "$root/Service.qml" || true)
[[ $eq_gain_calls -eq 1 ]] || fail "eqBandGains must run once; sliders bind to reals, got $eq_gain_calls"
grep -q 'property bool gainPreview' "$root/Service.qml" && fail "gain preview must be gone"
grep -q 'onPresetChanged: { busyReason = "preset"' "$root/Service.qml" || fail "preset must restart the host"
grep -q 'busyReason = "engine"' "$root/Service.qml" || fail "engine must restart the host"
grep -q 'busyReason = "target"' "$root/Service.qml" || fail "mic switch must mark the duck"
grep -q 'busyReason = "reload"' "$root/Service.qml" || fail "reload must mark the duck"
grep -q 'function hostSwitchReason' "$root/Model.js" || fail "host switch reason must live in Model"
grep -q 'id: heroIcon' "$root/Panel.qml" || fail "header must use the Omavoice mark"
grep -q 'id: powerSwitch' "$root/Panel.qml" || fail "on/off must be the original pill toggle"
grep -q 'id: powerButton' "$root/Panel.qml" && fail "power icon button must be gone"
grep -q 'busy: service.busy && !service.running' "$root/Panel.qml" && fail "preset switch must not spin the power switch"
grep -q 'busyReason === "preset"' "$root/Panel.qml" || fail "selected preset chip must dim while the host is down"
grep -q 'busyReason === "engine"' "$root/Panel.qml" || fail "selected engine chip must dim while the host is down"
grep -q 'busyReason === "target"' "$root/Panel.qml" || fail "selected mic row must dim while the host is down"
grep -q 'Switching microphone' "$root/Model.js" || fail "mic switch copy must name the duck"
grep -q 'Reloading' "$root/Model.js" || fail "reload copy must name the duck"
grep -q 'function showTune' "$root/Panel.qml" || fail "preset settings must flip to a tune page"
grep -q 'id: presetTuneButton' "$root/Panel.qml" || fail "PRESET needs a settings action"
grep -q 'id: presetRow' "$root/Panel.qml" || fail "preset chips must live in presetRow"
grep -A12 'id: presetRow' "$root/Panel.qml" | grep -q 'HoverHandler' || fail "preset hover must clear when the cursor leaves the chips"
grep -q 'id: sourceList' "$root/Panel.qml" || fail "mic rows must live in sourceList"
grep -A8 'id: sourceList' "$root/Panel.qml" | grep -q 'HoverHandler' || fail "mic hover must clear when the cursor leaves the list"
grep -q 'id: engineRow' "$root/Panel.qml" || fail "engine chips must live in engineRow"
grep -A8 'id: engineRow' "$root/Panel.qml" | grep -q 'HoverHandler' || fail "engine hover must match preset chips"
grep -q 'focusSection === "engine"' "$root/Panel.qml" || fail "engine chips must use the same cursor as presets"
grep -q 'id: voiceRow' "$root/Panel.qml" || fail "Voice looks must live in voiceRow"
grep -A12 'id: voiceRow' "$root/Panel.qml" | grep -q 'HoverHandler' || fail "Voice hover must match preset chips"
grep -q 'focusSection === "voice"' "$root/Panel.qml" || fail "Voice chips must use the same cursor as presets"
grep -q 'function setChipHover' "$root/Panel.qml" || fail "chip hover must share one enter/leave helper"
grep -q 'iconText: "󰒓"' "$root/Panel.qml" || fail "preset tuning must use a settings icon"
grep -q 'text: "AUTOMATIC"' "$root/Panel.qml" || fail "MICROPHONE must use the network AUTOMATIC toggle"
grep -q 'id: pageFlip' "$root/Panel.qml" || fail "tune page must animate like HEY"
grep -q 'label: "Default microphone"' "$root/Panel.qml" && fail "default mic must not live on a settings dump"
grep -q 'viewBox="0 0 24 24"' "$root/microphone.svg" || fail "microphone.svg must be the square mic mark"
grep -q 'the record button' "$root/README.md" && fail "README must not talk about a record button"

grep -q 'setListen' "$root/Service.qml" && fail "Listen must be gone from Service"
grep -q 'listenProcess' "$root/Service.qml" && fail "Listen process must be gone"
grep -q 'pw-loopback' "$root/Service.qml" && fail "pw-loopback must be gone"
grep -q 'toggleListen' "$root/Panel.qml" && fail "Listen must be gone from Panel"
grep -q 'Listen (use headphones)' "$root/Panel.qml" && fail "Listen row must be gone"
grep -q 'id: beforePeakMonitor' "$root/Panel.qml" && fail "hero Before/After meters must be gone"
grep -q 'label: "Before"' "$root/Panel.qml" && fail "hero Before bar must be gone"

echo "qml.test: ok"
