#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fail() { echo "qml.test: $*" >&2; exit 1; }

grep -q 'id: afterPeakMonitor' "$root/Panel.qml" || fail "Panel needs afterPeakMonitor"
grep -q 'id: rowPeak' "$root/Panel.qml" || fail "each mic row needs a peak monitor"
grep -q 'PwNodePeakMonitor' "$root/Panel.qml" || fail "Panel must use PwNodePeakMonitor"
grep -q 'afterPeakMonitor.peak' "$root/Panel.qml" || fail "selected row must show After"
grep -q 'enabled: root.opened && root.metersArmed && !!node' "$root/Panel.qml" || fail "row meters must rebind after graph changes"
grep -q 'onAfterNodeNameChanged: syncMeterHold' "$root/Service.qml" || fail "hold must wait for the bound Omavoice name"
grep -q 'id: meterHoldWatch' "$root/Service.qml" || fail "hold must retry if it never started"
grep -q 'startDebounce' "$root/Service.qml" || fail "preset switches must debounce the host restart"
grep -q 'shouldDeferSourcePick' "$root/Service.qml" || fail "source pick must ignore unbound-name flicker"
grep -q 'Util.alpha' "$root/Panel.qml" || fail "meters must use Omarchy audio chrome"
grep -q 'setMeterHold' "$root/Service.qml" || fail "Service must expose setMeterHold"
grep -q 'pw-cat' "$root/Service.qml" || fail "Service must hold the graph with pw-cat"
grep -q '"--target", name' "$root/Service.qml" || fail "pw-cat must target the bound omavoice name"
grep -q '"--target", nodeId' "$root/Service.qml" && fail "pw-cat must not target Quickshell node ids"
grep -q 'node.dont-fallback=true' "$root/Service.qml" && fail "pw-cat dont-fallback prevents the meter hold from attaching"
grep -q '/dev/null' "$root/Service.qml" || fail "meter hold must discard audio"
grep -q 'afterNodeName' "$root/Service.qml" || fail "Service must expose the bound afterNodeName"
grep -q 'afterNode' "$root/Service.qml" || fail "Service must expose afterNode"
grep -q 'nodeNamed' "$root/Service.qml" || fail "Service must look up capture nodes by name"
grep -q '"version": "0.1.24"' "$root/manifest.json" || fail "manifest must be 0.1.24"
[[ -f "$root/preview.png" ]] || fail "marketplace needs root preview.png"
[[ -f "$root/docs/preview-tune.png" ]] || fail "preset tune screenshot must be in docs"
grep -q 'id: reloadButton' "$root/Panel.qml" || fail "header needs a reload next to on/off"
grep -q 'iconText: service.reloading ? "󰑓" : "󰑐"' "$root/Panel.qml" || fail "reload must use the HEY/Fizzy refresh icons"
grep -q 'function reload' "$root/Service.qml" || fail "Service must expose reload"
grep -q 'libdeep_filter_ladspa-bin' "$root/README.md" || fail "Podcast AUR package must be libdeep_filter_ladspa-bin"
grep -q 'deepfilternet-ladspa' "$root/README.md" && fail "deepfilternet-ladspa is not an AUR package"
grep -q 'mktemp' "$root/scripts/omavoice-run" || fail "--dump must write a temp conf, not the live host"
grep -q '!n.isSink && !n.isStream' "$root/Service.qml" || fail "tracker must bind sources only"
grep -q 'onNodesChanged: refreshSources' "$root/Service.qml" || fail "sources must refresh on PipeWire node changes"
grep -q 'plugins.omarchy.org' "$root/README.md" || fail "README must point at the official marketplace"
grep -q 'omarchyplugins.com' "$root/README.md" && fail "README must not use omarchyplugins.com"
[[ -e "$root/omavoice.png" ]] && fail "root omavoice.png leftover orb must be gone"
grep -q 'microphone.svg' "$root/OmavoiceIcon.qml" || fail "icon must use the microphone SVG"
grep -q 'docs/omavoice.svg' "$root/README.md" || fail "README must use the microphone banner"
grep -q 'Softer' "$root/Panel.qml" || fail "quality stops must be Softer / Balanced / Stronger"
grep -q 'qualityHint' "$root/Panel.qml" || fail "quality slider must explain the impact"
grep -q 'Your voice, better heard' "$root/README.md" || fail "README must keep the tagline"
grep -q 'component QualitySlider' "$root/Panel.qml" || fail "settings need a 3-stop quality slider"
grep -q 'meetingQuality' "$root/Service.qml" || fail "Service must expose meetingQuality"
grep -q '"--quality"' "$root/Service.qml" || fail "host must pass --quality"
grep -q 'id: heroIcon' "$root/Panel.qml" || fail "header must use the Omavoice mark"
grep -q 'id: powerSwitch' "$root/Panel.qml" || fail "on/off must be the original pill toggle"
grep -q 'id: powerButton' "$root/Panel.qml" && fail "power icon button must be gone"
grep -q 'function showTune' "$root/Panel.qml" || fail "preset settings must flip to a tune page"
grep -q 'id: presetTuneButton' "$root/Panel.qml" || fail "PRESET needs a settings action"
grep -q 'iconText: "󰒓"' "$root/Panel.qml" || fail "preset tuning must use a settings icon"
grep -q 'text: "AUTOMATIC"' "$root/Panel.qml" || fail "MICROPHONE must use the network AUTOMATIC toggle"
grep -q 'id: pageFlip' "$root/Panel.qml" || fail "tune page must animate like HEY"
grep -q 'label: "Default microphone"' "$root/Panel.qml" && fail "default mic must not live on a settings dump"
grep -q 'viewBox="0 0 24 24"' "$root/microphone.svg" || fail "microphone.svg must be the square mic mark"
grep -q 'the record button' "$root/README.md" && fail "README must not talk about a record button"

grep -q 'setListen' "$root/Service.qml" && fail "Listen must be gone from Service"
grep -q 'listenProcess' "$root/Service.qml" && fail "Listen process must be gone"
grep -q 'pw-loopback' "$root/Service.qml" && fail "pw-loopback must be gone"
grep -q 'toggleListen' "$root/Panel.qml" && fail "Listen must be gone from Panel"
grep -q 'Listen (use headphones)' "$root/Panel.qml" && fail "Listen row must be gone"
grep -q 'id: beforePeakMonitor' "$root/Panel.qml" && fail "hero Before/After meters must be gone"
grep -q 'label: "Before"' "$root/Panel.qml" && fail "hero Before bar must be gone"

echo "qml.test: ok"
