source = ./variables.conf
source = ./monitors.conf
source = ./workspaces.conf
source = ./keybinding.conf
source = ./navigation.conf
source = ./windowrule.conf
source = ./layout.conf
source = ./theme.conf
source = ./misc.conf

exec-once = ~/.scripts/theme.sh
exec-once = ~/.config/waybar/activate.sh
exec-once = /usr/lib/xfce-polkit/xfce-polkit
exec-once = hyprctl setcursor "Qogirr-Dark" 18
exec-once = gsettings set org.gnome.desktop.interface cursor-theme "Qogirr-Dark"
exec-once = sleep 5 && noisetorch -i && sleep 3 && ~/.scripts/volume.sh --mute-mic
exec-once = sleep 5 && blueman-applet

exec-once = nm-applet
exec-once = hyprpaper
exec-once = earlyoom
exec-once = mako

exec-once = brave --profile-directory=Default 
# exec-once = google-chrome-stable --disable-features=WaylandWpColorManagerV1
# exec-once = microsoft-edge-stable --disable-features=WaylandWpColorManagerV1
# exec-once = brave --profile-directory=Default --app-id=hnpfjngllnobngcgfapefoaidbinmjnm # whatsapp
# exec-once = brave --profile-directory=Default --app-id=dlgohinmglaoopaiplliaecdpmnepmga # todoist

# keyd is used to remap esc to capslock
# /etc/keyd/default.conf
# sudo systemctl enable --now keyd
# sudo systemctl disable --now keyd
