source = ./variables.conf
source = ./monitors.conf
source = ./workspaces.conf
source = ./keybinding.conf
source = ./navigation.conf
source = ./windowrule.conf
source = ./layout.conf
source = ./hyprtoolkit.conf
source = ./misc.conf

exec-once = ~/.config/scripts/theme.sh
exec-once = ~/.config/scripts/monitor-auto-switch.sh
exec-once = ~/.config/waybar/activate.sh

exec-once = sleep 5 && noisetorch -i && sleep 3 && ~/.config/scripts/volume.sh --mute-mic
exec-once = hyprctl setcursor "Qogirr-Dark" 18
exec-once = gsettings set org.gnome.desktop.interface cursor-theme "Qogirr-Dark"
exec-once = systemctl --user start hyprpolkitagent

exec-once = hypridle
exec-once = hyprpaper
exec-once = hyprsunset

exec-once = earlyoom
exec-once = mako

exec-once = brave --profile-directory=Default 
exec-once = brave --profile-directory=Default --app-id=hnpfjngllnobngcgfapefoaidbinmjnm # whatsapp
exec-once = brave --profile-directory=Default --app-id=dlgohinmglaoopaiplliaecdpmnepmga # todoist

# keyd is used to remap esc to capslock
# /etc/keyd/default.conf
# sudo systemctl enable --now keyd
# sudo systemctl disable --now keyd
