-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Shenzhen KTC Technology Group SFPCCB24180 000000000000",
  mode = "1920x1080@120.00",
  position = "170x30",
  scale = 1,
  bitdepth = 10,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:SUE SFP2412FHD 000000000000",
  mode = "1920x1080@120.00",
  position = "2090x30",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Lenovo Group Limited 0x40A9",
  disabled = true,
})
