source = ./hyprvariables.conf
source = ./hyprbinds.conf
source = ./hyprnavigation.conf
source = ./hyprwindowrule.conf
source = ./hyprtoolkit.conf
source = ./hyprmisc.conf
source = ./monitors.conf
source = ./workspaces.conf

# exec-once = ~/.config/scripts/monitor.sh
exec-once = xdg-user-dirs-update
exec-once = ~/.config/scripts/theme.sh
exec-once = ~/.config/scripts/waybar.sh

exec-once = sleep 4 && pactl set-default-source effect_output.rnnoise && pactl set-source-mute effect_output.rnnoise 1
exec-once = hyprctl setcursor "Qogirr-Dark" 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme "Qogirr-Dark"
exec-once = /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 # mate-polkit
exec-once = valent --gapplication-service
exec-once = mako

exec-once = hypridle
exec-once = systemctl --user enable --now hyprpaper.service
exec-once = systemctl --user enable --now hyprsunset.service
exec-once = systemctl --user enable --now hyprdynamicmonitors.service

exec-once = sleep 2 && brave --profile-directory=Default

# keyd is used to remap esc to capslock
# /etc/keyd/default.conf
# sudo systemctl enable --now keyd
# sudo systemctl disable --now keyd
