max-gamma = 150

profile {
    time = 19:00
    temperature = 6000
}
profile {
    time = 20:00
    temperature = 5500
}
profile {
    time = 21:00
    temperature = 5000
}
profile {
    time = 4:00
    temperature = 5500
}
profile {
    time = 5:00
    temperature = 6000
}
profile {
    time = 6:00
    temperature = 6500
}
