-- Generated by nwg-displays on 2026-08-31 at 10:08:44. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "DP-3",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "DP-4",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1,
    vrr = 0
})
