#-- Variables --------------------------------------------------
# Colors
$gradient_angle = 45deg
$active_border_col_1 = 0xFFf38ba8
$active_border_col_2 = 0xFFeba0ac
$inactive_border_col_1 = 0xFF313244
$inactive_border_col_2 = 0xFF313244
$active_shadow_col = 0x00FFFFFF
$inactive_shadow_col = 0x00FFFFFF

#-- General ----------------------------------------------------
general {
	border_size = 2
	gaps_in = 4
	gaps_out = 8
	col.active_border = $active_border_col_1 $active_border_col_2 $gradient_angle 
	col.inactive_border = $inactive_border_col_1 $inactive_border_col_2 $gradient_angle
	layout = dwindle
}

#-- Decoration -------------------------------------------------
decoration {
	rounding = 2
}

#-- Animations -------------------------------------------------
animations {
	enabled = true
	animation = windowsIn,1,5,default,popin 0%
	animation = windowsOut,1,5,default,popin
	animation = windowsMove,1,5,default,slide
	animation = fadeIn,1,8,default
	animation = fadeOut,1,8,default
	animation = fadeSwitch,1,8,default
	animation = fadeShadow,1,8,default
	animation = fadeDim,1,8,default
	animation = border,1,10,default
	animation = workspaces,1,5,default,fade
}

#-- Catppuccin Mocha Theme ------------------------------------
$rosewaterAlpha = f5e0dc
$rosewater = rgb($rosewaterAlpha)

$flamingoAlpha = f2cdcd
$flamingo = rgb($flamingoAlpha)

$pinkAlpha = f5c2e7
$pink = rgb($pinkAlpha)

$mauveAlpha = cba6f7
$mauve = rgb($mauveAlpha)

$redAlpha = f38ba8
$red = rgb($redAlpha)

$maroonAlpha = eba0ac
$maroon = rgb($maroonAlpha)

$peachAlpha = fab387
$peach = rgb($peachAlpha)

$yellowAlpha = f9e2af
$yellow = rgb($yellowAlpha)

$greenAlpha = a6e3a1
$green = rgb($greenAlpha)

$tealAlpha = 94e2d5
$teal = rgb($tealAlpha)

$skyAlpha = 89dceb
$sky = rgb($skyAlpha)

$sapphireAlpha = 74c7ec
$sapphire = rgb($sapphireAlpha)

$blueAlpha = 89b4fa
$blue = rgb($blueAlpha)

$lavenderAlpha = b4befe
$lavender = rgb($lavenderAlpha)

$textAlpha = cdd6f4
$text = rgb($textAlpha)

$subtext1Alpha = bac2de
$subtext1 = rgb($subtext1Alpha)

$subtext0Alpha = a6adc8
$subtext0 = rgb($subtext0Alpha)

$overlay2Alpha = 9399b2
$overlay2 = rgb($overlay2Alpha)

$overlay1Alpha = 7f849c
$overlay1 = rgb($overlay1Alpha)

$overlay0Alpha = 6c7086
$overlay0 = rgb($overlay0Alpha)

$surface2Alpha = 585b70
$surface2 = rgb($surface2Alpha)

$surface1Alpha = 45475a
$surface1 = rgb($surface1Alpha)

$surface0Alpha = 282828
$surface0 = rgb($surface0Alpha)

$baseAlpha = 1e1e2e
$base = rgb($baseAlpha)

$mantleAlpha = 181825
$mantle = rgb($mantleAlpha)

$crustAlpha = 11111b
$crust = rgb($crustAlpha)
