$SUPER = SUPER
$MONITOR1 = desc:SUE SFP2412FHD 000000000000
$MONITOR2 = desc:Shenzhen KTC Technology Group SFPCCB24180 000000000000

$Ç1 = code:47
$Ç2 = code:108
$F13 = code:191
$F14 = code:192
$F15 = code:193
$F16 = code:194
$F17 = code:195
$F18 = code:196

$backlight   = ~/.config/scripts/brightness.sh
$volume      = ~/.config/scripts/volume.sh
$focus       = ~/.config/scripts/focus.sh
$keyd        = ~/.config/scripts/keyd.sh
$powermenu   = ~/.config/scripts/powermenu.sh
$explorer    = "nemo ~/Downloads"

$brave_flags = --max-unused-resource-memory-usage-mb=128 --disk-cache-size=67108864

$brave = "brave --profile-directory=Default $brave_flags"
$brave_ = brave-browser

$devbot = "brave --profile-directory=brave-devbot --class=brave-devbot --user-data-dir=.brave-devbot $brave_flags"
$devbot_ = brave-devbot

$maistodos = "brave --profile-directory=brave-maistodos --class=brave-maistodos --user-data-dir=.brave-maistodos $brave_flags"
$maistodos_ = brave-maistodos

$ytmusic = "brave --profile-directory=Default --app-id=cinhimbnkkaeohfgghhklpknlkffjgod $brave_flags"
$ytmusic_ = brave-cinhimbnkkaeohfgghhklpknlkffjgod-Default

$whatsapp = "brave --profile-directory=Default --app-id=hnpfjngllnobngcgfapefoaidbinmjnm $brave_flags"
$whatsapp_ = brave-hnpfjngllnobngcgfapefoaidbinmjnm-Default

$todoist = "brave --profile-directory=Default --app-id=dlgohinmglaoopaiplliaecdpmnepmga $brave_flags"
$todoist_ = brave-dlgohinmglaoopaiplliaecdpmnepmga-Default


