source = ./variables.conf

# Next empty workspace
windowrule = match:class $brave_, workspace emptyn
windowrule = match:class $brave_, monitor $MONITOR1

windowrule = match:class $devbot_, workspace emptyn
windowrule = match:class $devbot_, monitor $MONITOR2

windowrule = match:class $maistodos_, workspace emptyn
windowrule = match:class $maistodos_, monitor $MONITOR2

windowrule = match:class $ytmusic_, workspace emptyn
windowrule = match:class $ytmusic_, monitor $MONITOR2

windowrule = match:class $todoist_, workspace emptyn
windowrule = match:class $todoist_, monitor $MONITOR2

windowrule = match:class $whatsapp_, workspace emptyn
windowrule = match:class $whatsapp_, monitor $MONITOR2
