source = ./variables.conf

# Next empty workspace
windowrule = match:class $brave_, workspace emptyn
windowrule = match:class $devbot_, workspace emptyn
windowrule = match:class $maistodos_, workspace emptyn

# windowrule = match:class code, workspace emptyn
windowrule = match:class $ytmusic_, workspace emptyn
windowrule = match:class $todoist_, workspace emptyn
windowrule = match:class $whatsapp_, workspace emptyn
