source = ./variables.conf

windowrule {
    name = Floating Windows
    float = on
    match:class = blueman-manager
}
windowrule {
    name = Monitor 2
    monitor = $MONITOR2
    match:class = $whatsapp_
    match:class = $todoist_
    match:class = $ytmusic_
    match:class = Slack
}

windowrule = match:class $vscode_,      workspace 8,
windowrule = match:class kitty,         workspace 9,
windowrule = match:class $whatsapp_,    workspace 10, monitor $MONITOR2
windowrule = match:class $zen_,         workspace 11, monitor $MONITOR2
windowrule = match:class $chrome_,      workspace 12, monitor $MONITOR2
windowrule = match:class Slack,         workspace 13, monitor $MONITOR2
windowrule = match:class $todoist_,     workspace 14, monitor $MONITOR2
windowrule = match:class $ytmusic_,     workspace 15, monitor $MONITOR2