# Catppuccin Black Theme
$rosewaterAlpha = f5e0dc
$rosewater = rgb($rosewaterAlpha)

$flamingoAlpha = f2cdcd
$flamingo = rgb($flamingoAlpha)

$pinkAlpha = f5c2e7
$pink = rgb($pinkAlpha)

$mauveAlpha = cba6f7
$mauve = rgb($mauveAlpha)

$redAlpha = f38ba8
$red = rgb($redAlpha)

$maroonAlpha = eba0ac
$maroon = rgb($maroonAlpha)

$peachAlpha = fab387
$peach = rgb($peachAlpha)

$yellowAlpha = f9e2af
$yellow = rgb($yellowAlpha)

$greenAlpha = a6e3a1
$green = rgb($greenAlpha)

$tealAlpha = 94e2d5
$teal = rgb($tealAlpha)

$skyAlpha = 89dceb
$sky = rgb($skyAlpha)

$sapphireAlpha = 74c7ec
$sapphire = rgb($sapphireAlpha)

$blueAlpha = 89b4fa
$blue = rgb($blueAlpha)

$lavenderAlpha = b4befe
$lavender = rgb($lavenderAlpha)

$textAlpha = ffffff
$text = rgb($textAlpha)

$subtext1Alpha = b8b8b8
$subtext1 = rgb($subtext1Alpha)

$subtext0Alpha = 9e9e9e
$subtext0 = rgb($subtext0Alpha)

$overlay2Alpha = 5f5f5f
$overlay2 = rgb($overlay2Alpha)

$overlay1Alpha = 4f4f4f
$overlay1 = rgb($overlay1Alpha)

$overlay0Alpha = 3f3f3f
$overlay0 = rgb($overlay0Alpha)

$surface2Alpha = 2a2a2a
$surface2 = rgb($surface2Alpha)

$surface1Alpha = 232323
$surface1 = rgb($surface1Alpha)

$surface0Alpha = 1c1c1c
$surface0 = rgb($surface0Alpha)

$baseAlpha = 151515
$base = rgb($baseAlpha)

$mantleAlpha = 121212
$mantle = rgb($mantleAlpha)

$crustAlpha = 0f0f0f
$crust = rgb($crustAlpha)

# Colors
$gradient_angle = 45deg
$active_border_col_1 = 0xFF$redAlpha
$active_border_col_2 = 0xFF$maroonAlpha
$inactive_border_col_1 = 0xFF$subtext0Alpha
$inactive_border_col_2 = 0xFF$subtext0Alpha

background = 0xFF$mantleAlpha
base = 0xFF$baseAlpha
text = 0xFF$textAlpha
alternate_base = 0xFF$surface0Alpha
bright_text = 0xFF$subtext1Alpha
accent = 0xFF$redAlpha          
accent_secondary = 0xFF$maroonAlpha  

# Typography
h1_size = 22
h2_size = 19
h3_size = 17
font_size = 15
small_font_size = 12

# Font Families
icon_theme = Papirus
font_family = Sans Serif
font_family_monospace = monospace

# Rounding
rounding_large = 12
rounding_small = 12

# General
general {
	border_size = 2
	gaps_in = 3
	gaps_out = 8
	col.active_border = $active_border_col_1 $active_border_col_2 $gradient_angle 
	col.inactive_border = $inactive_border_col_1 $inactive_border_col_2 $gradient_angle
	layout = dwindle
}

# Decoration
decoration {
	rounding = 2
}

# Animations
animations {
	enabled = true
	animation = windowsIn,1,5,default,popin 0%
	animation = windowsOut,1,5,default,popin
	animation = windowsMove,1,5,default,slide
	animation = fadeIn,1,8,default
	animation = fadeOut,1,8,default
	animation = fadeSwitch,1,8,default
	animation = fadeShadow,1,8,default
	animation = fadeDim,1,8,default
	animation = border,1,10,default
	animation = workspaces,1,5,default,fade
}
