[accessibility]
ui_scale = 1.2

[bar.default]
background_opacity = 1.0
capsule = false
center = ["taskbar", "tray"]
concave_edge_corners = false
end = [
  "battery",
  "keyd",
  "lock_keys",
  "brightness",
  "input_volume",
  "audio_switcher",
  "bluetooth",
  "bar_2",
  "network",
  "calendar",
  "clock",
]
font_scale = 1.0
font_weight = 700
margin_edge = 5
margin_ends = 8
padding = 8
radius = 4
scale = 1.0
shadow = false
start = ["temp", "cpu", "ram", "disk", "brave_profile", "bar", "recorder"]
thickness = 27
widget_spacing = 6

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [
  "lockscreen-login-box@DP-6",
  "lockscreen-login-box@DP-5",
  "lockscreen-login-box@FALLBACK",
  "lockscreen-login-box@DP-4",
  "lockscreen-login-box@DP-3",
  "lockscreen-login-box@eDP-1",
]

[lockscreen_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
box_height = 196.0
box_width = 810.0
cx = 960.0
cy = 898.0
output = "DP-3"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true

[lockscreen_widgets.widget."lockscreen-login-box@DP-4"]
box_height = 196.0
box_width = 810.0
cx = 960.0
cy = 898.0
output = "DP-4"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@DP-4".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true

[lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
box_height = 196.0
box_width = 810.0
cx = 960.0
cy = 898.0
output = "DP-5"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@DP-5".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true

[lockscreen_widgets.widget."lockscreen-login-box@DP-6"]
box_height = 196.0
box_width = 810.0
cx = 960.0
cy = 898.0
output = "DP-6"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@DP-6".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true

[lockscreen_widgets.widget."lockscreen-login-box@FALLBACK"]
box_height = 196.0
box_width = 810.0
cx = 960.0
cy = 898.0
output = "FALLBACK"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@FALLBACK".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
box_height = 196.0
box_width = 810.0
cx = 960.0
cy = 807.0
output = "eDP-1"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true

[nightlight]
enabled = true
temperature_night = 4500

[plugin_settings."icefish/phone-connect"]
battery_display = "hidden"
show_device_name = true

[plugin_settings."blackbartblues/audio-switcher"]
show_actions_in_tooltip = true
show_notification_on_switch = true
show_percentage = true

[plugin_settings."icefish/phone-operate"]
battery_display = "hidden"
show_device_name = true

[plugin_settings."kenn/keybind-cheatsheet"]
compositor = "hyprland"
hyprland_lua_config = "~/.config/hypr/binds.lua"
hyprland_parser = "lua"

[plugin_settings."oldirtty/color_picker"]
panel_position = "top_left"

[plugins]
enabled = [
  "xonha/desktop-controls",
  "oldirtty/color_picker",
  "yuuto/calculator",
  "noctalia/screen_recorder",
  "noctalia/notes",
  "blackbartblues/keymap",
  "blackbartblues/audio-switcher",
  "raycursive/github-prs",
  "kenn/keybind-cheatsheet",
  "icefish/phone-connect",
]

[shell]
clipboard_image_action_command = "satty -f -"
launch_apps_as_systemd_services = true
polkit_agent = true
settings_show_advanced = true

[shell.animation]
speed = 1.2000000178813934

[shell.greeter_sync]
auto_sync = true

[shell.panel]
open_near_click_control_center = true
session_placement = "floating"
session_position = "center"

[shell.screenshot]
copy_to_clipboard = false
pipe_command = "satty -f -"
pipe_to_command = true
save_to_file = false

[[shell.session.actions]]
action = "lock"
countdown_seconds = 0.0
enabled = true
shortcut = "1"
variant = "default"

[[shell.session.actions]]
action = "logout"
countdown_seconds = 0.0
enabled = true
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "lock_and_suspend"
countdown_seconds = 3.0
enabled = true
shortcut = "3"
variant = "default"

[[shell.session.actions]]
action = "reboot"
countdown_seconds = 3.0
enabled = true
shortcut = "4"
variant = "default"

[[shell.session.actions]]
action = "shutdown"
countdown_seconds = 3.0
enabled = true
shortcut = "5"
variant = "destructive"

[system.monitor]
cpu_poll_seconds = 3
disk_poll_seconds = 30
gpu_poll_seconds = 2
memory_poll_seconds = 10

[theme]
builtin = "Catppuccin"
community_palette = "Oxocarbon"
custom_palette = "Catppuccin-Black"
mode = "dark"
source = "custom"
wallpaper_scheme = "m3-tonal-spot"

[theme.templates]
builtin_ids = ["btop", "kcolorscheme", "kitty", "qt", "alacritty"]

[wallpaper.default]
path = "/home/henrique/.wallpaper.jpg"

[wallpaper.last]
path = "/home/henrique/.wallpaper.jpg"

[wallpaper.monitors.DP-3]
path = "/home/henrique/.wallpaper.jpg"

[wallpaper.monitors.DP-4]
path = "/home/henrique/.wallpaper.jpg"

[widget.bar]
color = "#f2cdcd"
enabled = false
hide_when_zero = true
scale = 1.1000000000000001
type = "raycursive/github-prs:bar"

[widget.bar_2]
font_scale = 1.1000000000000001
scale = 1.2000000000000002
type = "icefish/phone-connect:bar"

[widget.battery]
color = "#a6e3a1"
show_label = true

[widget.bluetooth]
color = "#89b4fa"
show_label = true

[widget.brave_profile]
color = "#f5e0dc"
type = "xonha/desktop-controls:brave-profile"

[widget.brightness]
color = "#89dceb"
show_label = true

[widget.calendar]
type = "xonha/desktop-controls:calendar"

[widget.calendar.actions]
left = "panel-toggle control-center calendar"
scroll_down = "volume-down"
scroll_up = "volume-up"

[widget.clock]
color = "#cba6f7"
format = "{:%H:%M}"

[widget.clock.actions]
left = "panel-toggle control-center notifications"
scroll_down = "volume-down"
scroll_up = "volume-up"

[widget.cpu]
color = "#eba0ac"
show_value = true
stat = "cpu_usage"
type = "sysmon"
visualization = "none"

[widget.disk]
color = "#f9e2af"
highlight_color = "#f9e2af"
path = "/"
show_value = true
stat = "disk_free"
type = "sysmon"
visualization = "none"

[widget.input_volume]
type = "xonha/desktop-controls:input_volume"

[widget.keyd]
color = "#94E2D5"
icon_color = "#94E2D5"
type = "xonha/desktop-controls:keyd"

[widget.launcher]
color = "secondary"

[widget.lock_keys]
display = "full"
icon_color = "#94E2D5"
type = "xonha/desktop-controls:lock_keys"

[widget.media]
hide_when_no_media = true

[widget.network]
type = "xonha/desktop-controls:network"

[widget.network.actions]
left = "panel-toggle control-center network"
right = "network-toggle"

[widget.audio_switcher]
type = "blackbartblues/audio-switcher:widget"

[widget.ram]
color = "#fab387"
show_value = true
stat = "ram_used"
type = "sysmon"
visualization = "none"

[widget.recorder]
enabled = false
scale = 1.2000000000000002
type = "noctalia/screen_recorder:recorder"

[widget.status]
font_weight = 700
scale = 1.0
type = "icefish/phone-connect:bar"

[widget.taskbar]
active_opacity = 1.0
group_by_workspace = false
inactive_opacity = 1.0
item_spacing = 4
show_active_indicator = true
show_all_outputs = false

[widget.temp]
color = "#f38ba8"
show_value = true
stat = "cpu_temp"
type = "sysmon"
visualization = "none"
